FROM node:24-alpine as build

# podman build -t adminapp . -f Dockerfile.web
# podman start adminapp -p 5171:5171 --name adminapp-1

# WORKDIR ProblemSource/AdminApp
WORKDIR /usr/src/app

COPY ProblemSource/AdminApp/package.json .

RUN echo "First copy result" 
RUN ls -ltR 

RUN npm install
# apk add curl

COPY ProblemSource/AdminApp/ .

RUN echo "Second copy result" 
RUN ls -ltR 

ENV NODE_ENV=docker

RUN npm run build

COPY ProblemSource/AdminApp/mime.types /usr/src/app/build/


# Stage 2
FROM node:24-alpine

COPY --from=build /usr/src/app/build /usr/share/html

RUN npm install -g http-server

EXPOSE 5171
ENV PORT=5171

# https://stackoverflow.com/questions/61106423/how-to-put-a-svelte-app-in-a-docker-container
# CMD [ "http-server",  "build", "--proxy", "http://localhost:5171?"]
CMD http-server /usr/share/html --proxy http://localhost:5171/index.html? --mimetypes /usr/share/html/mime.types
# --mimetypes mime.types

# cd ~/source/repos/JWMB/WebProcessor
# podman build -t adminapp . -f Dockerfile.web