FROM node:24-alpine

# WORKDIR ProblemSource/AdminApp
WORKDIR /app

# nothing copied? COPY ProblemSource/AdminApp/* /
# works, but too much copied?
COPY ProblemSource/AdminApp/** /

# COPY ./ProblemSource/AdminApp/** ./
# COPY ./ProblemSource/AdminApp/package.json ./
# COPY ./ProblemSource/AdminApp/src/** ./src/
# COPY package*.json ./

# RUN find -maxdepth 2 -ls
# no output..
RUN ls -ltR 

RUN npm install
# RUN npm install -g http-server
# apk add curl

COPY . .

RUN npm run build

EXPOSE 5171

# https://stackoverflow.com/questions/61106423/how-to-put-a-svelte-app-in-a-docker-container
# CMD [ "http-server",  "ProblemSource/AdminApp/build", "--proxy", "http://localhost:5171?"]

CMD ["npm", "run", "start"]
# CMD ["npm", "run", "dev", "--", "--host"]

# podman build -t adminapp . -f Dockerfile.web