using System.Text.Json.Serialization;

namespace Common.LLM
{
	// Temp until common nuget
	public interface ILlmService
	{
		Task<LlmResult?> Invoke(string prompt, LlmCallOptions? options = null);
		//string Get(string prompt, int maxTokens = 1000, double temperature = 0, TimeSpan timeout = default, CancellationToken cancellation = default);
		int CountTokens(string text);
		LlmModelSpecification ModelSpecification { get; }
	}
	public record LlmContentReceivedData(string ContentSinceLast, int TotalLength);


	public class LlmModelSpecification
	{
		public List<string> AvailableOnServices { get; set; } = new();
		public string Name { get; set; } = string.Empty;
		public string? DeploymentName { get; set; }
		public int MaxContextTokens { get; set; }
		public int MaxAttentionSpanTokens { get; set; }
		public string? TokenizerName { get; set; }
	}

	public class LlmServiceSpecification
	{
		public required string Name { get; set; }
		public required string ApiKey { get; set; }
		public required string ResourceUri { get; set; }
	}

	public class LlmCallOptions()
	{
		public int MaxTokens { get; set; } = 20000;
		public double Temperature { get; set; } = 0;
		public TimeSpan Timeout { get; set; } = default;
		public Action<LlmContentReceivedData>? ContentReceived { get; set; }
	}

	public class LlmResult
	{
		public (int Input, int Output) Tokens { get; set; }
		public string? Completion { get; set; } = "";
		public string Model { get; set; } = "";
	}

	public class AzureOpenAIRESTService : ILlmService
	{
		private readonly Config config;
		public record Config(Uri ResourceUri, string ApiKey, string DeploymentName);

		public LlmModelSpecification ModelSpecification { get; private set; }

		//private bool IsEnabled = true;
		//public record Config(Uri ResourceUri, string ApiKey, string DeploymentName);

		public AzureOpenAIRESTService(LlmModelSpecification modelSpecification, LlmServiceSpecification serviceSpecification)
		{
			ModelSpecification = modelSpecification;
			config = new Config(
				new Uri(serviceSpecification.ResourceUri), //.GetHostParts().First(),
				serviceSpecification.ApiKey,
				modelSpecification.DeploymentName ?? modelSpecification.Name);
		}

		public async Task<LlmResult?> Invoke(string prompt, LlmCallOptions? options = null)
		{
			options ??= new LlmCallOptions();
			var apiVersion = "2025-04-01-preview";
			//var uri = new Uri($"https://{config.ResourceUri}.openai.azure.com/openai/responses?api-version={apiVersion}");
			var uri = new Uri($"{config.ResourceUri}openai/responses?api-version={apiVersion}");
			var request = new HttpRequestMessage(HttpMethod.Post, uri);
			request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", config.ApiKey);

			var body = new
			{
				input = prompt,
				max_output_tokens = options.MaxTokens, //max_completion_tokens = maxTokens,
				model = ModelSpecification.DeploymentName,
				//temperature = options.Temperature // Unsupported parameter: 'temperature' is not supported with this model.
			};
			request.Content = new StringContent(System.Text.Json.JsonSerializer.Serialize(body), new System.Net.Http.Headers.MediaTypeHeaderValue("application/json"));

			var client = new HttpClient();
			try
			{
				var response = await client.SendAsync(request);
				var content = await response.Content.ReadAsStringAsync();

				var typed = System.Text.Json.JsonSerializer.Deserialize<AutoGeneratedResponseClasses.Root>(content);

				if (typed == null)
					throw new Exception($"Error deserializing response ({content})");
				if (typed.Error != null)
					throw new Exception(typed.Error.Message);

				if (typed.IncompleteDetails != null)
				{ }
				if (typed.Metadata != null)
				{ }
				return new LlmResult
				{
					Completion = string.Join("\n", typed.Output.SelectMany(o => o.Content?.Select(c => c.Text).OfType<string>() ?? [])),
					Tokens = new(typed.Usage.InputTokens ?? 0, typed.Usage.OutputTokens ?? 0),
					Model = typed.Model == null ? throw new NullReferenceException() : ModelSpecification.Name ?? ""
				};
			}
			catch (HttpRequestException hrEx) when (hrEx.Message.Contains("No such host is known"))
			{
				throw;
			}
			catch (Exception ex)
			{
				throw;
			}
		}

		public int CountTokens(string text)
		{
			var name = ModelSpecification.Name ?? ModelSpecification.DeploymentName;
			return 0; // name.IsNullOrEmpty() ? 0 : new TiktokenCounter(name).CountTokens(text);
		}


		public class AutoGeneratedResponseClasses
		{
			// Root myDeserializedClass = JsonSerializer.Deserialize<Root>(myJsonResponse);
			public class Content
			{
				[JsonPropertyName("type")]
				public required string Type { get; set; }

				[JsonPropertyName("text")]
				public string? Text { get; set; }

				[JsonPropertyName("annotations")]
				public List<object>? Annotations { get; set; }
			}

			public class Format
			{
				[JsonPropertyName("type")]
				public string? Type { get; set; }
			}

			public class InputTokensDetails
			{
				[JsonPropertyName("cached_tokens")]
				public int? CachedTokens { get; set; }
			}

			public class Metadata
			{
			}

			public class Output
			{
				[JsonPropertyName("type")]
				public string? Type { get; set; }

				[JsonPropertyName("id")]
				public string? Id { get; set; }

				[JsonPropertyName("status")]
				public string? Status { get; set; }

				[JsonPropertyName("role")]
				public string? Role { get; set; }

				[JsonPropertyName("content")]
				public List<Content> Content { get; set; } = new();
			}

			public class OutputTokensDetails
			{
				[JsonPropertyName("reasoning_tokens")]
				public int? ReasoningTokens { get; set; }
			}

			public class Reasoning
			{
				[JsonPropertyName("effort")]
				public object? Effort { get; set; }

				[JsonPropertyName("summary")]
				public object? Summary { get; set; }
			}

			public class Root
			{
				[JsonPropertyName("id")]
				public string? Id { get; set; }

				[JsonPropertyName("object")]
				public string? Object { get; set; }

				[JsonPropertyName("created_at")]
				public int? CreatedAt { get; set; }

				[JsonPropertyName("status")]
				public string? Status { get; set; }

				[JsonPropertyName("error")]
				public Error? Error { get; set; }

				[JsonPropertyName("incomplete_details")]
				public object? IncompleteDetails { get; set; }

				[JsonPropertyName("instructions")]
				public object? Instructions { get; set; }

				[JsonPropertyName("max_output_tokens")]
				public object? MaxOutputTokens { get; set; }

				[JsonPropertyName("model")]
				public string? Model { get; set; }

				[JsonPropertyName("output")]
				public List<Output> Output { get; set; } = new();

				[JsonPropertyName("parallel_tool_calls")]
				public bool? ParallelToolCalls { get; set; }

				[JsonPropertyName("previous_response_id")]
				public object? PreviousResponseId { get; set; }

				[JsonPropertyName("reasoning")]
				public Reasoning? Reasoning { get; set; }

				[JsonPropertyName("store")]
				public bool? Store { get; set; }

				[JsonPropertyName("temperature")]
				public double? Temperature { get; set; }

				[JsonPropertyName("text")]
				public Text? Text { get; set; }

				[JsonPropertyName("tool_choice")]
				public string? ToolChoice { get; set; }

				[JsonPropertyName("tools")]
				public List<object>? Tools { get; set; }

				[JsonPropertyName("top_p")]
				public double? TopP { get; set; }

				[JsonPropertyName("truncation")]
				public string? Truncation { get; set; }

				[JsonPropertyName("usage")]
				public required Usage Usage { get; set; }

				[JsonPropertyName("user")]
				public object? User { get; set; }

				[JsonPropertyName("metadata")]
				public Metadata? Metadata { get; set; }
			}

			public class Error
			{
				[JsonPropertyName("message")]
				public required string Message { get; set; }

				[JsonPropertyName("type")]
				public required string Type { get; set; }

				[JsonPropertyName("param")]
				public object? Param { get; set; }

				[JsonPropertyName("code")]
				public required string Code { get; set; }
			}
			public class Text
			{
				[JsonPropertyName("format")]
				public Format? Format { get; set; }
			}

			public class Usage
			{
				[JsonPropertyName("input_tokens")]
				public int? InputTokens { get; set; }

				[JsonPropertyName("input_tokens_details")]
				public InputTokensDetails? InputTokensDetails { get; set; }

				[JsonPropertyName("output_tokens")]
				public int? OutputTokens { get; set; }

				[JsonPropertyName("output_tokens_details")]
				public OutputTokensDetails? OutputTokensDetails { get; set; }

				[JsonPropertyName("total_tokens")]
				public int? TotalTokens { get; set; }
			}

		}
	}
}
